// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package ORM

import (
	"database/sql"
)

type Account struct {
	Uuid        string
	Teamuuid    sql.NullString
	Username    string
	Password    string
	Mailaddress string
	Isquit      int64
}

type AwsCredential struct {
	Uuid         string
	Region       string
	ID           string
	Secret       string
	Bucketid     string
	Bucketprefix sql.NullString
}

type Mail struct {
	Uuid      string
	Boxuuid   string
	Header    string
	Sentat    string
	Createdat string
	Size      int64
}

type MailBox struct {
	Uuid      string
	Name      string
	Owneruuid string
}

type Session struct {
	Uuid        string
	Accountuuid string
}

type Team struct {
	Uuid           string
	Name           string
	Description    sql.NullString
	Credentialuuid string
}
